routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Front-end
Route::get('/','Front\PublicController@index')->name('public.index');
Route::get('/product/details/{id}','Front\PublicController@product')->name('public.product.details');

//Login
Route::get('/login','Front\LoginController@login')->name('login');
Route::post('/login/store','Front\LoginController@store')->name('login.store');

//Register
Route::get('/register','Front\LoginController@register')->name('register');
Route::post('/register/store','Admin\UsersController@store')->name('register.store');

//Logout
Route::get('/logout','Front\LoginController@logout')->name('logout');



//Admin
Route::group(['prefix'=>'admin','middleware'=>['auth'=>'admin']],function() {
    //Admin Dashboard
    Route::get('/', 'Admin\DashboardController@index')->name('admin.dashboard');
    //Products
    Route::resource('/products', 'Admin\ProductsController');
    //Orders
    Route::get('/orders', 'Admin\OrdersController@index')->name('orders.index');
    Route::get('/orders/show/{id}', 'Admin\OrdersController@show')->name('orders.show');
    Route::get('/orders/pending/{id}', 'Admin\OrdersController@pending')->name('order.pending');
    Route::get('/orders/confirm/{id}', 'Admin\OrdersController@confirm')->name('order.confirm');
    //Users
    Route::get('/users', 'Admin\UsersController@index')->name('users.index');
    Route::get('/users/show/{id}', 'Admin\UsersController@show')->name('users.show');
    Route::post('/users/store', 'Admin\UsersController@store')->name('users.store');
    Route::post('/users/update', 'Admin\UsersController@update')->name('users.update');

    //Message
    Route::get('/message/', 'Admin\MessageController@index')->name('message.index');
    Route::post('/message/store', 'Admin\MessageController@store')->name('message.store');
    Route::post('/message/delete/{id}', 'Admin\MessageController@destroy')->name('message.destroy');



});



//Buyer
Route::group(['prefix'=>'buyer','middleware'=>['auth'=>'buyer']],function() {

    //Buyer profile page
    Route::get('/profile','Buyer\ProfileController@index')->name('buyer.index');
    Route::get('/profile/edit/{id}','Buyer\ProfileController@edit')->name('buyer.edit');
    Route::post('/profile/update/{id}','Admin\UsersController@update')->name('buyer.update');
    Route::get('/profile/show/{id}','Buyer\ProfileController@show')->name('buyer.show');
    Route::get('/profile/details/{id}','Buyer\ProfileController@details')->name('buyer.details');


    //ShoppingCart
    Route::get('/shoppingCart', 'Buyer\ShoppingCartController@index')->name('shoppingCart.index');
    Route::post('/shoppingCart/store', 'Buyer\ShoppingCartController@store')->name('shoppingCart.store');
    Route::post('/shoppingCart/quantity/{id}', 'Buyer\ShoppingCartController@quantity')->name('shoppingCart.quantity');
    Route::post('/shoppingCart/destroy/{id}', 'Buyer\ShoppingCartController@destroy')->name('shoppingCart.destroy');
    //Checkout
    Route::get('/checkout', 'Buyer\ShoppingCartController@proceed')->name('shoppingCart.checkout');
    //Store Delivery address
    Route::post('/checkout/store', 'Admin\OrdersController@store')->name('shoppingCart.store');
    //Store Order + Products in pivot table
    Route::post('checkout/pay', 'Admin\OrdersController@pay')->name('order.pay');



});

resources/views/admin/includes/footer.blade.php
<footer class="footer" style="background-color: #636b6f;">
    <div class="container-fluid">

        <div class="copyright pull-right" style="color:white;">
            All Rights Reserved by <a href="" style="font-size: 18px;font-weight: bolder;color:mediumspringgreen;">Tea Kljajin</a>
            &copy;
            <script>document.write(new Date().getFullYear())</script>

        </div>
    </div>
</footer>

resources/views/admin/includes/header.blade.php
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <link rel="icon" type="image/png" sizes="96x96" href="{{asset('assets/img/favicon.png')}}">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>

    <title>@yield('title')</title>

    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport'/>
    <meta name="viewport" content="width=device-width"/>



    <link rel="stylesheet" href="{{asset('assets/css/animate.min.css')}}">
    <link rel="stylesheet" href="{{asset('assets/css/paper-dashboard.css')}}">
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Muli:400,300">
    <link rel="stylesheet" href="{{asset('assets/css/themify-icons.css')}}">
    <link rel="stylesheet" href="{{asset('assets/css/bootstrap.min.css')}}">

</head>

resources/views/admin/includes/navbar.blade.php
<nav class="navbar navbar-default" style="background-color:#696969;">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar bar1"></span>
                <span class="icon-bar bar2"></span>
                <span class="icon-bar bar3"></span>
            </button>
            <a class="navbar-brand" href="#" style="color:lightseagreen">Dashboard</a>
            <a class="navbar-brand" href="{{route('public.index')}}" style="color:white;"> Home</a>
        </div>
        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav navbar-right">

                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" style="color:lightseagreen">
                        <i class="ti-settings"></i>
                        <p style="font-weight: bolder;"><i class="fa fa-user"></i> {{Auth::user()->name}}</p>
                        <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                        <li><a href="{{route('logout')}}">Logout</a></li>
                    </ul>
                </li>
            </ul>

        </div>
    </div>
</nav>

resources/views/admin/includes/scripts.blade.php
<script src="{{asset('assets/js/jquery-1.10.2.js')}}"></script>
<script src="{{asset('assets/js/bootstrap.min.js')}}"></script>
<script src="{{asset('assets/js/thumbnailImage.js')}}"></script>
<script src="{{asset('assets/js/scripts.js')}}"></script>

</body>

</html>

resources/views/admin/includes/sidebar.blade.php
<div class="sidebar" data-background-color="dark" data-active-color="danger">

    <div class="sidebar-wrapper" style="background-color: #696969;">
        <div class="logo">
            <a href="" class="simple-text" style="color:white;font-weight: bolder;font-size: 20px;font-family:Arial;">
                PizzaShop Admin
            </a>
        </div>

        <ul class="nav">
            <li>
                <a href="{{route('admin.dashboard')}}" style="color:white">
                    <i class="ti-panel"></i>
                    <p style="font-size: 18px;text-transform: capitalize;">Dashboard</p>
                </a>
            </li>
            <li>
                <a href="{{route('products.index')}}" style="color:white;">
                    <i class="ti-archive"></i>
                    <p style="font-size: 18px;text-transform: capitalize;">Product</p>
                </a>
            </li>

            <li>
                <a href="{{route('orders.index')}}" style="color:white;">
                    <i class="ti-calendar"></i>
                    <p style="font-size: 18px;text-transform: capitalize;">Orders</p>
                </a>
            </li>
            <li>
                <a href="{{route('users.index')}}" style="color:white">
                    <i class="fa fa-users"></i>
                    <p style="font-size: 18px;text-transform: capitalize;">Users</p>
                </a>
            </li>
            <li>
                <a href="{{route('message.index')}}" style="color:white">
                    <i class="fa fa-pencil"></i>
                    <p style="font-size: 18px;text-transform: capitalize;">Messages</p>
                </a>
            </li>
        </ul>
    </div>



</div>